name: Publish release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
